apiVersion: v1
kind: Pod
metadata:
  name: kubia-label
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports: 
        - containerPort: 8080