apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - image: nginx:alpine
      name: web-server
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: nginx-configmap